### ISSUE TITLE
Wrong text color for post content

### ISSUE THREAD

**Issue by zemzale** [zemzale/ohm#2]
Text color inside the post looks like this 
![image](https://cloud.githubusercontent.com/assets/14844365/24981070/ac3337ca-1fe3-11e7-970e-9ac1f4f40a6f.png)
but I am preaty sure its supposed to look like this
![image](https://cloud.githubusercontent.com/assets/14844365/24981104/d60d4216-1fe3-11e7-93a7-112b41c114b1.png)

It looks like this from `css/theme.css`
```
body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
  line-height: 1.42857143;
  color: #494949;
  background-color: #222222;
}
```
conflicts with this from `css/style.css`
```
body {
    background-color: #454545;
    background-image: url("../img/bg.png");
    font-family: 'Share Tech Mono', monospace;
    color: #FFF;
}
```

@dotSplit

**Comment by dotSplit** [comment]
That's because style.css should be declared after theme.css

**Comment by dotSplit** [comment]
Fixed in Design branch
